config/routes.rb
Rails.application.routes.draw do
  root 'store#index', as: 'store'

  # routes for products


   get    'products/:id/who_bought' => 'products#who_bought', as: :who_bought_product

   get    'products/' =>  'products#index',    as: :products

   get 'products/men/' => 'products#men', as: :men

   get 'products/women' => 'products#women', as: :women

   get 'products/accessories' => 'products#accessories', as: :accessories

  post   'products/' =>   'products#create'

  get    'products/new' =>       'products#new', as: :new_product

  get    'products/:id' =>       'products#show',     as: :product

  get    'products/:id/edit' =>  'products#edit', as: :edit_product

  patch  'products/:id' =>       'products#update'



  delete 'products/:id' =>       'products#destroy'

  # routes for store
  get 'store/:id' => 'store#show', as: :show_store

  # routes for carts

  get    'carts/' =>  'carts#index',    as: :carts

  post   'carts/' =>   'carts#create'

  get    'carts/new' =>       'carts#new', as: :new_cart

  get    'carts/:id' =>       'carts#show',     as: :cart

  get    'carts/:id/edit' =>  'carts#edit', as: :edit_cart

  patch  'carts/:id' =>       'carts#update'

  delete 'carts/:id' =>       'carts#destroy'

  # routes for line_items

  get    'line_items/' =>  'line_items#index',    as: :line_items

  post   'line_items/' =>   'line_items#create'

  get    'line_items/new' =>       'line_items#new', as: :new_line_item

  # get    'line_items/:id' =>       'line_items#show',     as: :line_item

  get    'line_items/:id/edit' =>  'line_items#edit', as: :edit_line_item

  patch  'line_items/:id' =>       'line_items#update'

  delete 'line_items/:id' =>       'line_items#destroy'

  # routes for orders

  get    'orders/' =>  'orders#index',    as: :orders

  post   'orders/' =>   'orders#create'

  get    'orders/new' =>       'orders#new', as: :new_order

  get    'orders/:id' =>       'orders#show',     as: :order

  get    'orders/:id/edit' =>  'orders#edit', as: :edit_order

  patch  'orders/:id' =>       'orders#update'

  delete 'orders/:id' =>       'orders#destroy'

  # routes for users

  get    'users/' =>  'users#index',    as: :users

  post   'users/' =>   'users#create'

  get    'users/new' =>       'users#new', as: :new_user

  get    'users/:id' =>       'users#show',     as: :user

  get    'users/:id/edit' =>  'users#edit', as: :edit_user

  patch  'users/:id' =>       'users#update'

  delete 'users/:id' =>       'users#destroy'

  # routes for sessions //new //create //destory

  get    'sessions/' =>  'sessions#index',    as: :sessions

   controller :sessions do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
   end

  




  # get 'orders/new' => 'orders#new', as: :new_order

end

app/models/product.rb
class Product < ActiveRecord::Base
  
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  
  has_many :line_items
  has_many :orders, through: :line_items
  before_destroy :ensure_not_referenced_by_any_line_item

  #...

  validates :title, :description, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
# 
  validates :title, uniqueness: true


  def self.latest
    Product.order(:updated_at).last
  end

  private

    # ensure that there are no line items referencing this product
    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line Items present')
        return false
      end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  def men
    @products = Product.all
  end

  def women
    @products = Product.all
  end

  def accessories
    @products = Product.all
  end
  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to sessions_path,
          notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created,
          location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors,
          status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to sessions_path,
          notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors,
          status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to sessions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white
    # list through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :category, :avatar)
    end
end

app/views/products/accessories.html.erb
<div class="product-title">
  <h1>Accessories</h1>
</div>


<br><br><br>
  <% cache ['store', Product.latest] do %>
  <div class="product-list">
    <% @products.each do |product| %>
      <% cache ['entry', product] do %>
        <%if product.category == "accessories"%>
          <div class="product">

            <%= product.title %> | 
            <%= product.description %> | 
            <%= number_to_currency(product.price) %> |
            <%= product.category %><br>
            <%= image_tag product.avatar.url(:medium) %><br>
          
            <%= button_to 'Add to Cart', line_items_path(product_id: product) %><br>
          </div>
        <% end %>
      <% end %>
    <% end %>
    </div>
  <% end %>

app/views/products/create.html.erb
create.html.erb

app/views/products/edit.html.erb
<h1> Edit this product! </h1>



<%= form_for(@product) do |f| %>

    <%= f.label :title %><br>
    <%= f.text_field :title %>

    <%= f.label :description %><br>
    <%= f.text_area :description, rows: 6 %>

    <%= f.label :price %><br>
    <%= f.text_field :price %>

    <%= f.label :category %><br>
    <%= f.text_field :category %>


    <%= f.file_field :avatar %>


    <%= f.submit %>

<% end %>

<br>

<%= link_to 'back to list of products', products_path%>

app/views/products/index.html.erb
<br><br><br>

<% cache ['store', Product.latest] do %>
  <% @products.each do |product| %>
    <% cache ['entry', product] do %>
      <%= product.title %><br>
      <%= product.description %><br>
      <%= product.price %><br>
      <%= image_tag product.avatar.url(:medium) %><br>     
      <%= button_to 'Add to Cart', line_items_path(product_id: product) %><br>

    <% end %>
  <% end %>
<% end %>

app/views/products/men.html.erb
<div class="product-title">
  <h1>Men's T-Shirts</h1>
</div>

<br><br><br>
  <% cache ['store', Product.latest] do %>
  <div class="product-list">
    <% @products.each do |product| %>
      <% cache ['entry', product] do %>
        <%if product.category == "men"%>
          <div class="product">

            <%= product.title %> | 
            <%= product.description %> | 
            <%= number_to_currency(product.price) %> |
            <%= product.category %><br>
            <%= image_tag product.avatar.url(:medium) %><br>
          
            <%= button_to 'Add to Cart', line_items_path(product_id: product) %><br>
          </div>
        <% end %>
      <% end %>
    <% end %>
    </div>
  <% end %>

app/views/products/new.html.erb
<h1>New product</h1>

<div class = "new-product">
<%= form_for(@product) do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %><br>

	<%= f.label :description %>
	<%= f.text_area :description, rows: 6 %><br>

	<%= f.label :price %>
	<%= f.text_field :price %><br>

	<%= f.label :category %>
    <%= f.text_field :category %><br>

	<%= f.file_field :avatar %><br>


	<%= f.submit %>
<%end%>
</div>

<br>

<%= link_to 'back to list of products', products_path%>

app/views/products/show.html.erb
show.html.erb

app/views/products/women.html.erb
<div class="product-title">
  <h1>Women's T-Shirts</h1>
</div>

<br><br><br>
  <% cache ['store', Product.latest] do %>
  <div class="product-list">
    <% @products.each do |product| %>
      <% cache ['entry', product] do %>
        <%if product.category == "women"%>
          <div class="product">

            <%= product.title %> | 
            <%= product.description %> | 
            <%= number_to_currency(product.price) %> |
            <%= product.category %><br>
            <%= image_tag product.avatar.url(:medium) %><br>
          
            <%= button_to 'Add to Cart', line_items_path(product_id: product) %><br>
          </div>
        <% end %>
      <% end %>
    <% end %>
    </div>
  <% end %>