config/routes.rb
Rails.application.routes.draw do
  root 'store#index', as: 'store'

  # routes for products


   get    'products/:id/who_bought' => 'products#who_bought', as: :who_bought_product

   get    'products/' =>  'products#index',    as: :products

   get 'products/men/' => 'products#men', as: :men

   get 'products/women' => 'products#women', as: :women

   get 'products/accessories' => 'products#accessories', as: :accessories

  post   'products/' =>   'products#create'

  get    'products/new' =>       'products#new', as: :new_product

  get    'products/:id' =>       'products#show',     as: :product

  get    'products/:id/edit' =>  'products#edit', as: :edit_product

  patch  'products/:id' =>       'products#update'



  delete 'products/:id' =>       'products#destroy'

  # routes for store
  get 'store/:id' => 'store#show', as: :show_store

  # routes for carts

  get    'carts/' =>  'carts#index',    as: :carts

  post   'carts/' =>   'carts#create'

  get    'carts/new' =>       'carts#new', as: :new_cart

  get    'carts/:id' =>       'carts#show',     as: :cart

  get    'carts/:id/edit' =>  'carts#edit', as: :edit_cart

  patch  'carts/:id' =>       'carts#update'

  delete 'carts/:id' =>       'carts#destroy'

  # routes for line_items

  get    'line_items/' =>  'line_items#index',    as: :line_items

  post   'line_items/' =>   'line_items#create'

  get    'line_items/new' =>       'line_items#new', as: :new_line_item

  # get    'line_items/:id' =>       'line_items#show',     as: :line_item

  get    'line_items/:id/edit' =>  'line_items#edit', as: :edit_line_item

  patch  'line_items/:id' =>       'line_items#update'

  delete 'line_items/:id' =>       'line_items#destroy'

  # routes for orders

  get    'orders/' =>  'orders#index',    as: :orders

  post   'orders/' =>   'orders#create'

  get    'orders/new' =>       'orders#new', as: :new_order

  get    'orders/:id' =>       'orders#show',     as: :order

  get    'orders/:id/edit' =>  'orders#edit', as: :edit_order

  patch  'orders/:id' =>       'orders#update'

  delete 'orders/:id' =>       'orders#destroy'

  # routes for users

  get    'users/' =>  'users#index',    as: :users

  post   'users/' =>   'users#create'

  get    'users/new' =>       'users#new', as: :new_user

  get    'users/:id' =>       'users#show',     as: :user

  get    'users/:id/edit' =>  'users#edit', as: :edit_user

  patch  'users/:id' =>       'users#update'

  delete 'users/:id' =>       'users#destroy'

  # routes for sessions //new //create //destory

  get    'sessions/' =>  'sessions#index',    as: :sessions

   controller :sessions do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
   end

  




  # get 'orders/new' => 'orders#new', as: :new_order

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyStore</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
  <!-- bootstrap -->
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
</head>
<body>

<!-- start bootstrap navbar -->
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	        <div class="container">
	            <!-- Brand and toggle get grouped for better mobile display -->
	            <div class="navbar-header">
	                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	                    <span class="sr-only">Toggle navigation</span>
	                    <span class="icon-bar"></span>
	                    <span class="icon-bar"></span>
	                    <span class="icon-bar"></span>
	                </button>
	                <a class="navbar-brand" href="../#">Store Home</a>
	            </div>
	            <!-- Collect the nav links, forms, and other content for toggling -->
	            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	                <ul class="nav navbar-nav">
	                    <li>
	                        <a href="#">About</a>
	                    </li>
	                    <li>
	                        <a href="#">Services</a>
	                    </li>
	                    <li>
	                        <a href="#">Contact</a>
	                    </li>
						
						<% if !session[:user_id] %>
		                    <li class = "right1">
		                    	<%= link_to 'Sign Up', new_user_path %> | 
		                    </li>
		                    <li class = "right2">
		                    	<%= link_to 'Log In', login_path%> 
		                    </li>
		                 <% end %>
	                    <% if session[:user_id] %>
		                    <li class = "right1">
		                    	<%= link_to 'Edit Products', sessions_path %> | 
		                    </li>
		                    <li>
		                    	<%= link_to 'Logout', logout_path, method: :delete   %>
		                    </li>
	                    
	                    <% end %>
	                </ul>
	            </div>
	            <!-- /.navbar-collapse -->
	        </div>
	        <!-- /.container -->
	    </nav>
	    <br><br><br><br>
<!-- end bootstrap navbar -->


 	<%= yield %>



<!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p class="center">Copyright &copy; Cosimo Inc 2014</p>
            </div>
        </div>
    </footer>

</body>
</html>